// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uukulcagkypsgguzzaei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1a3VsY2Fna3lwc2dndXp6YWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwODc0OTAsImV4cCI6MjA4MjY2MzQ5MH0.AuTgMvIUtKrAlKtW7Rmvmxt0TNexORxheF71Q1tqE6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);